name: Deploy to Vercel

on:
  push:
    branches:
      - master  # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Specify the Node.js version (adjust as needed)

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build --prod  # This command builds the project

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20 --yes
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}  # Vercel token
          vercel-project: ${{ secrets.VERCEL_PROJECT }}  # Your Vercel project name
          github-token: ${{ secrets.GITHUB_TOKEN }}  # Automatically provided by GitHub
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT: ${{ secrets.VERCEL_PROJECT }}  # Your project name
